name: Test deployment

on: 
  pull_request:
    branches: 
      - 'master'

env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=16384

jobs:
  
  dummy-deploy:
    name: dummy-deploy     
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: start deployment
        uses: Tallyb/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: my-mockup
          ref: ${{github.sha}}
          transient: true

      - name: update deployment status
        uses: Tallyb/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          desc: my mockup
          env_url: https://google.com
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          
